port: "8080"

db:
  host: "localhost"
  port: "5436"
  username: "postgres"
  dbname: "postgres"
  sslmode: "disable"

smtp:
  host: "smtp.gmail.com"
  port: 587
  sender_email: "biketracker.ua@gmail.com"